---
title: "Lake color analysis"
author: "Xiao Yang"
date: "1/31/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(tidyverse)
require(sf)
require(foreach)
```


## Jida's lake data three regions

```{r}
calc_hue_density = function(hue) {
  
  d = density(hue, n = 512)
  
  hue_density = tibble(hue = d$x, density = d$y) %>% 
    filter(hue >= 0, hue <= 1) %>% 
    mutate(rgb_color = hsv(h = hue, s = 1, v = 1))
  
  return(hue_density)
}
calc_hue_color_bar = function(n = 100) {
  return(tibble(hue = seq(0, 1, length = n)) %>% mutate(rgb_color = hsv(h = hue, s = 1, v = 1)))
}

## import the dataset

fileinfo = tibble(
  filedir = c(
    "data/mean_lake_color_roi1_8ba054ab336634e127d548f925681daf.csv",
    "data/mean_lake_color_roi2_dd85cb7c10dd310b1d3d1c93de39514c.csv",
    "data/mean_lake_color_roi3_c4549c94182362691561ca5712438d23.csv"
  ),
  region = c(
    "Tibetan Plateau",
    "Minnesota + Wisconsin",
    "Mackenzie Delta"
  ))

dat = foreach(i = 1:nrow(fileinfo), .combine = "bind_rows") %do% {
  read_csv(file = fileinfo$filedir[i]) %>% 
    mutate(region = fileinfo$region[i])
} %>% 
    select(-`.geo`) %>% 
    rename(img_id = `system:index`)

## need to handle the different date string position in the image ID

dat = dat %>% 
  filter(cloudAndShadow == 0,
         snowAndIce == 0,
         Red >= 0,
         Red <= 10000,
         Green >= 0,
         Green <= 10000,
         Blue >= 0,
         Blue <= 10000,
         !is.na(hue)) %>% 
  mutate(img_id_rev = stringi::stri_reverse(img_id)) %>% 
  separate(col = img_id_rev, into = c(NA, NA, NA, "satellite"), sep = "_") %>% 
  mutate(satellite = paste0("Landsat ", substr(satellite, start = 1, stop = 1))) %>% 
  select(
    -BQA,
    -cloudAndShadow,
    -snowAndIce,
    -uBlue
  )

lake_id = dat %>% 
  select(clon, clat) %>% 
  distinct()

lake_id = lake_id %>% 
  mutate(lake_id = 1:nrow(.))

dat = dat %>% 
  left_join(lake_id, by = c("clon", "clat"))

save(dat, file = "outputs/lake_color_three_regions_20200205.RData")

load("outputs/lake_color_three_regions_20200205.RData", verbose = T)


## range of values of hsv
dat %>% 
  gather(key = hsv, value = "value", c(hue, saturation, value)) %>% 
  select(hsv, value) %>% 
  ggplot() +
  geom_density(aes(value, fill = hsv), alpha = 0.3)

# remove lakes with high brightness value and low saturation
dat = dat %>%
  filter(saturation >= 0.125,
         value <= 0.125)

dat %>% 
  select(region, lake_id) %>% 
  distinct() %>% 
  group_by(region) %>% 
  count() %>% 
  ungroup


## regional distribution

hue_density_region = dat %>% 
  mutate(month = factor(month(date), levels = 1:12, labels = month.abb)) %>% 
  group_by(region) %>% 
  do({
    calc_hue_density(.$hue)
  }) %>% 
  ungroup
  
all_lake_color_region = hue_density_region %>% 
  ggplot(aes(hue, density)) + 
  geom_segment(aes(xend = hue, yend = 0, color = rgb_color), alpha = 0.7) + 
  geom_line(lwd = 1) + 
  scale_color_identity() +
  scale_x_continuous(limits = c(0, 1)) +
  labs(
    x = "Hue"
  ) +
  theme(
    panel.background = element_blank(),
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  ) +
  facet_wrap(~region, ncol = 1)

all_lake_color_region

all_lake_color_region %>% 
  ggsave(filename = "figures/all_lake_color_three_regions_20200205.png",
         width = 6,
         height = 6,
         dpi = 300)


## monthly breakdown

hue_density = dat %>% 
  mutate(month = factor(month(date), levels = 1:12, labels = month.abb)) %>% 
  group_by(region, month) %>% 
  do({
    calc_hue_density(.$hue)
  }) %>% 
  ungroup
  
all_lake_color = hue_density %>% 
  ggplot(aes(hue, density)) + 
  geom_segment(aes(xend = hue, yend = 0, color = rgb_color), alpha = 0.7) + 
  geom_line(lwd = 1) + 
  scale_color_identity() +
  scale_x_continuous(limits = c(0, 1), expand = c(0, 0)) +
  labs(
    y = "Density"
  ) +
  theme(
    panel.background = element_blank(),
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  ) +
  facet_grid(month~region, scales = "free_y")

all_lake_color

all_lake_color %>% 
  ggsave(filename = "figures/all_lake_color_three_regions_monthly_20200205.png",
         width = 6,
         height = 7,
         dpi = 300)


## per lake density plot

hue_density_lake = dat %>% 
  right_join(dat %>% 
              group_by(lake_id) %>% 
              summarise(n = n()) %>% 
              ungroup() %>% 
              filter(n >= 30), by = "lake_id") %>% 
  group_by(lake_id) %>% 
  do({
    dat_temp = .
    calc_hue_density(dat_temp$hue) %>% 
      mutate(n = nrow(dat_temp)) %>% 
      mutate(region = dat_temp$region[1],
             clon = dat_temp$clon[1],
             clat = dat_temp$clat[1])
  }) %>% 
  ungroup()

yshift = hue_density_lake %>% 
  group_by(lake_id) %>% 
  summarize(ymax = max(density),
            region = first(region)) %>% 
  arrange(ymax) %>% 
  ungroup() %>% 
  group_by(region) %>% 
  mutate(yshift = 1:n()) %>% 
  ungroup()
  

hue_density_lake = hue_density_lake %>% 
  left_join(yshift, by = c("lake_id", "region"))

yscale = hue_density_lake %>% group_by(lake_id, region) %>% summarize(stats = median(density)) %>% ungroup() %>% 
  group_by(region) %>% 
  summarise(scale = quantile(stats, probs = 0.3)) %>% 
  ungroup

hue_density_lake = hue_density_lake %>% 
  left_join(yscale, by = "region")

lake_color_per_lake = hue_density_lake %>% 
  ggplot(aes(hue, density + yshift * scale)) + 
  # geom_segment(data = calc_hue_color_bar(n = 512), aes(x = hue, y = 0, xend = hue, yend = hue_density_lake$density %>% max * 0.02, color = rgb_color), alpha = 1) +
  # geom_line(aes(group = Hylak_id), alpha = 0.1) +
  geom_segment(aes(xend = hue, yend = yshift * scale, color = rgb_color, group = lake_id), alpha = 0.1) + 
  scale_color_identity() +
  scale_x_continuous(limits = c(0, 1), expand = c(0, 0)) +
  labs(
    y = "Density"
  ) +
  theme(
    panel.background = element_rect(color = "black", fill = "black"),
    panel.grid = element_blank(),
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  ) +
  facet_wrap(~region, nrow = 1)

lake_color_per_lake

lake_color_per_lake %>% 
  ggsave(filename = "figures/three_regions_lake_color_per_lake_20200205.png",
         width = 15,
         height = 6,
         dpi = 100)

## map mode color
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}

color_mode = hue_density_lake %>% 
  group_by(lake_id, region) %>% 
  summarise(hue_mode = hue[which.max(density)],
            clon = first(clon),
            clat = first(clat)) %>% 
  ungroup() %>% 
  mutate(rgb_color = hsv(h = hue_mode, s = 1, v = 1))

color_mode_sf = color_mode %>% 
  st_as_sf(coords = c("clon", "clat"), crs = 4326)

mapview::mapview(color_mode_sf, zcol = "hue_mode", color = hsv(h = seq(0.1311, 0.4514, length = 100), s = 1, v = 1), fill = NA)
```


## seasonality

```{r}
require(lubridate)

doy_hue = dat %>% 
  mutate(doy = yday(date)) %>% 
  group_by(lake_id, doy) %>% 
  summarise(mean_hue = mean(hue),
            mean_sat = mean(saturation),
            region = first(region),
            date = first(date)) %>% 
  ungroup()

lake_color_seasonality = doy_hue %>% 
  mutate(plotcolor = hsv(h = mean_hue, s = mean_sat, v = 0.7)) %>% 
  ggplot() +
  geom_point(aes(x = doy, y = mean_hue, group = lake_id, color = plotcolor), alpha = 0.7, size = 0.05) +
  labs(x = "Day of the year",
       y = "Hue") +
  ylim(0, 0.75) +
  scale_color_identity() +
  facet_wrap(~region) +
  theme(
    # panel.background = element_rect(color = "black", fill = "black"),
    # panel.grid = element_blank(),
    # axis.title.y = element_blank(),
    # axis.text.y = element_blank(),
    # axis.ticks.y = element_blank()
  )

lake_color_seasonality

lake_color_seasonality %>% 
  ggsave(
    filename = "figures/lake_color_seasonality_filtered_20200205.png",
    width = 7,
    height = 3,
    dpi = 300
  )

## color index

doy_hue_index = doy_hue %>% 
  mutate(greenness = abs(mean_hue - 0.3),
         blueness = abs(mean_hue - 0.6),
         brownness = abs(mean_hue - 0.1))

greenness_mw = doy_hue_index %>% 
  filter(region == "Minnesota + Wisconsin") %>% 
  ggplot() +
  geom_smooth(aes(x = doy, y = greenness, group = lake_id), lwd = 0.1, se = F, show.legend = F, color = "darkgreen") +
  geom_point(aes(doy, y = greenness), size = 0.1, alpha = 0.1) + 
  geom_smooth(aes(x = doy, y = greenness), color = "green") +
  scale_y_reverse(minor_breaks = NULL, breaks = c(0.025, 0.275), labels = c("More green", "Less green"), lim = c(0.3, 0)) +
  labs(x = "Day of the year",
       y = "Greenness (hue ref: 0.3)",
       title = "Greenness for lakes from Minnesota + Wisconsin") +
  theme(axis.text.y.left = element_text(angle = 90, hjust = 0.5),
        axis.ticks.y = element_blank(),
        panel.grid.major.y = element_blank())

greenness_mw

greenness_mw %>% ggsave(
  filename = "figures/mw_greenness_20200205.png",
  width = 8,
  height = 5,
  dpi = 300
)

brownness_mk = doy_hue_index %>% 
  filter(region == "Mackenzie Delta") %>% 
  ggplot() +
  geom_smooth(aes(x = doy, y = brownness, group = lake_id), lwd = 0.1, se = F, show.legend = F, color = "brown") +
  geom_point(aes(doy, y = brownness), size = 0.1, alpha = 0.2) + 
  geom_smooth(aes(x = doy, y = brownness), color = "yellow") +
  scale_y_reverse(minor_breaks = NULL, breaks = c(0.025, 0.475), labels = c("More brown", "Less brown")) +
  labs(x = "Day of the year",
       y = "Brownness (ref hue: 0.1)",
       title = "Brownness for lakes from Mackenzie Delta") +
  theme(axis.text.y.left = element_text(angle = 90, hjust = 0.5),
        axis.ticks.y = element_blank(),
        panel.grid.major.y = element_blank())

brownness_mk

brownness_mk %>% ggsave(
  filename = "figures/mk_brownness_20200205.png",
  width = 8,
  height = 5,
  dpi = 300
)

doy_hue_index %>% 
  filter(region == "Tibetan Plateau") %>% 
  ggplot() +
  geom_smooth(aes(x = doy, y = blueness, group = lake_id), lwd = 0.1, se = F, show.legend = F, color = "darkblue") +
  geom_point(aes(doy, y = blueness), size = 0.1, alpha = 0.3) + 
  geom_smooth(aes(x = doy, y = blueness), color = "blue") +
  # ylim(0, 0.3) +
  labs(x = "Day of the year",
       y = "Blueness")
```

## time series

```{r}
set.seed(2020)
sublakes = dat %>% 
  select(lake_id, region) %>% 
  distinct() %>% 
  group_by(region) %>% 
  sample_n(100) %>% 
  ungroup()

sublakes %>%
  left_join(dat, by = c("lake_id", "region")) %>% 
  filter(date >= "2013-01-01") %>% 
  mutate(plot_color = hsv(h = hue, s = 1, v = 1)) %>% 
  ggplot(aes(x = date, y = hue, color = plot_color)) +
  geom_line(aes(group = lake_id), lwd = 0.1, color = "black", alpha = 0.4) +
  geom_point(size = 0.2) +
  scale_color_identity() +
  facet_wrap(~region, ncol = 1)
```

## monthly dominant colors

```{r}
require(lubridate)
load("outputs/lake_color_three_regions_20200205.RData", verbose = T)

monthly = dat %>% 
  mutate(month = factor(month(date), levels = 1:12, labels = month.name)) %>% 
  filter(date >= as.Date("2014-01-01"))

monthly %>% 
  filter(region == "Mackenzie Delta",
         lake_id == 877) %>% 
  ggplot() +
  geom_density(aes(x = hue, color = month, group = month))
  # geom_histogram(aes(x = hue, color = month))

month_mod_color = monthly %>% 
  group_by(lake_id, month) %>% 
  mutate(n = n()) %>% 
  ungroup() %>% 
  filter(n > 2) %>% 
  group_by(lake_id, month) %>% 
  do({
    dat = .
    d = density(dat$hue)
    tibble(mod_hue = d$x[which.max(d$y)]) %>% 
      mutate(clon = dat$clon[1],
             clat = dat$clat[1],
             region = dat$region[1])
  }) %>% 
  ungroup() %>% 
  mutate(plotcolor = hsv(h = mod_hue, s = 1, v = 0.7, alpha = 0.3))

save(month_mod_color, file = "monthly_mod_color.RData")


require(ggmap)
require(gganimate)

region_bbox = month_mod_color %>% 
  group_by(region) %>% 
  summarise(lat_min = min(clat),
            lat_max = max(clat),
            lon_min = min(clon),
            lon_max = max(clon)) %>% 
  ungroup()

region_index = 3

this_region_bbox = region_bbox[region_index, ]
this_region = this_region_bbox$region

map = get_stamenmap(c(
  this_region_bbox$lon_min, 
  this_region_bbox$lat_min, 
  this_region_bbox$lon_max, 
  this_region_bbox$lat_max), maptype = "terrain", zoom = 8)

multipanel_map = ggmap(map, darken = c(0.7, "black")) +
  geom_point(data = month_mod_color %>% 
            filter(region == this_region), mapping = aes(x = clon, y = clat, color = plotcolor, group = month), alpha = 0.7) +
  scale_color_identity() +
  labs(title = paste("Lake color seasonality: ", this_region),
     x = "Longitude",
     y = "Latitude") +
  facet_wrap(~month) +
  theme(title = element_text(size = 14))

# multipanel_map

multipanel_map %>% 
  ggsave(filename = paste0("figs/", this_region, "_monthly_maps.png"), 
         width = 10,
         height = 8,
         dpi = 300)

g = ggmap(map, darken = c(0.7, "black")) +
  geom_point(data = month_mod_color %>% 
            filter(region == this_region), mapping = aes(x = clon, y = clat, color = plotcolor, group = month), alpha = 0.8) +
  scale_color_identity() +
  labs(title = "Lake color seasonality: {month.name[frame_time]}",
       x = "Longitude",
       y = "Latitude") +
  transition_time(time = as.integer(month)) +
  theme(title = element_text(size = 18))

anim_save(filename = paste0(this_region, "_monthly_animation.gif"), animation = g, duration = 12, path = "figs", end_pause = 10)
```

## cluster analysis

```{r}
# https://www.statmethods.net/advstats/cluster.html

load("outputs/lake_color_three_regions_20200205.RData", verbose = T)

dat = dat %>%
  filter(date >= as.Date("2010-01-17"))

lake_info = dat %>% 
  select(clon, clat, lake_id, region) %>% 
  distinct()


monthly_data = dat %>% 
  mutate(month = factor(month(date), levels = 1:12, labels = month.abb)) %>%
  group_by(lake_id, month) %>% 
  mutate(n = n()) %>% 
  ungroup() %>% 
  filter(n > 2) %>% 
  group_by(lake_id, month) %>% 
  do({
    dat = .
    d = density(dat$hue)
    tibble(mod_hue = d$x[which.max(d$y)]) %>% 
      mutate(clon = dat$clon[1],
             clat = dat$clat[1],
             region = dat$region[1],
             mean_hue = mean(dat$hue))
  }) %>% 
  ungroup() %>% 
  mutate(hue = mean_hue)

save(monthly_data, file = "outputs/monthly_data.RData")

month_range = tibble(
  region = c("Mackenzie Delta", "Minnesota + Wisconsin", "Tibetan Plateau"),
  min_month = c(6, 4, 4),
  max_month = c(9, 11, 12)
)

obs_monthly_dist = monthly_data %>% 
  ggplot() +
  geom_bar(aes(x = as.integer(month))) +
  scale_x_continuous(breaks = 1:12, labels = month.abb) +
  facet_wrap(~region, ncol = 1, scales = "free_y") +
  labs(x = "",
       y = "Count") +
  geom_segment(data = month_range, aes(x = min_month, y = 0, xend = max_month, yend = 0), color = "green", lwd = 2)

obs_monthly_dist

obs_monthly_dist %>% 
  ggsave(filename = "figs/obs_monthly_dist.png",
         width = 7,
         height = 7)
  
# this_region = "Mackenzie Delta"
# this_region = "Minnesota + Wisconsin"
this_region = "Tibetan Plateau"

temp = month_range %>% filter(region == this_region)

training = monthly_data %>% 
  filter(region == this_region) %>% 
  filter(as.integer(month) >= temp$min_month[1], as.integer(month) <= temp$max_month[1]) %>% 
  select(month, hue, lake_id) %>% 
  group_by(lake_id) %>% 
  mutate(
    mean_hue = mean(hue),
    sd_hue = sd(hue),
    hue_norm = (hue - mean_hue) / sd_hue,
         ) %>% 
  ungroup() %>% 
  select(-hue) %>% 
  spread(key = month, value = hue_norm, fill = NA) %>% 
  na.omit()


mean_sd = training %>% 
  select(lake_id, mean_hue, sd_hue) %>% 
  distinct()




N = 3

### kmeans cluster

fit_kmeans = kmeans(training %>% select(-lake_id, -mean_hue, -sd_hue), N) # 5 cluster solution

# plotcluster(training %>% select(-lake_id), fit$cluster)
# library(cluster)
# clusplot(training %>% select(-lake_id), fit$cluster, color = TRUE, shade = TRUE,
#    labels = 0, lines = 0)

clustered = training %>% 
  mutate(class = fit_kmeans$cluster,
         method = "K-means")
  

month_names = (fit_kmeans$centers %>% dimnames())[[2]]

cluster_means = fit_kmeans$centers %>% 
  t() %>% 
  as_tibble() %>% 
  bind_cols(tibble(month_nm = month_names)) %>% 
  gather(key = "class", value = "hue", -month_nm) %>% 
  inner_join(tibble(month = 1:12, month_nm = month.abb)) %>% 
  mutate(method = "K-means")

### DTW based clustering

library(dtw)
library(TSclust)
library(dtwclust)
library(zoo)

training_dtw = training %>% 
  select(-lake_id, -mean_hue, -sd_hue) %>% 
  as.matrix()

cluster_dtw = tsclust(training_dtw, type = "h", k = N, distance = "dtw_basic",
                      centroid = dba, control =hierarchical_control(method = "complete"),
                      preproc = NULL)

## append class 

clustered = clustered %>% 
  bind_rows(clustered %>% 
              mutate(class = cluster_dtw@cluster,
                     method = "DTW"))
clustered = clustered %>% mutate(class = as.character(class))

## reconstruct cluster  mean
centroids = cluster_dtw@centroids
names(centroids) = paste0(1:N)
centroids = as_tibble(centroids) %>% 
  t() %>% 
  as_tibble()
names(centroids) = month_names
centroids = centroids %>% 
  mutate(class_dtw = 1:N) %>% 
  gather(key = "month_nm", value = "hue", -class_dtw) %>% 
  rename(class = class_dtw) %>% 
  mutate(method = "DTW") %>% 
  inner_join(tibble(month = 1:12, month_nm = month.abb), by = "month_nm")


merged_means = centroids %>% 
  mutate(class = as.character(class)) %>% 
  bind_rows(cluster_means)

# plot(cluster_dtw, type = "c", color = "grey") 
# 
# lake_id = training_all %>% 
#   bind_cols(tibble(cluster_dtw = this_clustering@cluster))
# 
# this_clustering_mean = this_clustering@centroid

## plot cluster results

estimated_doy = merged_means %>% 
  mutate(doy = yday(as.Date(paste0("2015-", month, "-15")))) %>% 
  inner_join(clustered)

cluster_center_fig = estimated_doy %>% 
  ggplot(aes(x = month, y = hue, color = class)) +
  geom_line(alpha = 0.7) +
  geom_point(size = 2) +
  facet_wrap(~method) +
  labs(
    x = "Month",
    y = "Normalized Hue",
    color = "Class"
  )

cluster_center_fig

cluster_center_fig %>% 
  ggsave(filename = paste0("figs/", this_region, "_cluster_center_fig.png"),
         width = 7,
         height = 5)

dat_clustered = dat %>% 
  select(lake_id, clat, clon, date, region, hue) %>% 
  mutate(doy = yday(date)) %>% 
  inner_join(clustered %>% 
               select(lake_id, 
                      class,
                      method), by = "lake_id")

doy_series_clustered = dat_clustered %>% 
  ggplot(aes(x = doy, y = hue, group = lake_id, color = class)) +
  geom_smooth(alpha = 0.2, lwd = 0.1, se = F) +
  facet_grid(method~class) +
  # scale_x_continuous(limits = c(150, 275)) +
  scale_color_viridis_d(end = 0.8) +
  labs(
    x = "DOY",
    y = "Hue",
    color = "Class"
  )

doy_series_clustered

doy_series_clustered %>% 
  ggsave(
    filename = paste0("figs/", this_region, "_doy_series_clustered.png"),
    width = 8,
    height = 6
  )

cluster_patterns = monthly_data %>%
  filter(region == this_region) %>%
  group_by(lake_id) %>%
  mutate(hue_norm = (hue - mean(hue)) / sd(hue)) %>%
  ungroup() %>%
  inner_join(clustered %>% select(-mean_hue), by = "lake_id") %>%
  ggplot() +
  # geom_smooth(aes(x = month, y = hue_norm, group = lake_id), alpha = 0.2, size = 0.1, se = F, method = 'loess', formula = 'y ~ x') +
  geom_line(aes(x = as.integer(month), y = hue_norm, group = lake_id), alpha = 0.5, size = 0.1) +
  geom_line(data = merged_means, aes(x = month, y = hue, color = "Cluster mean")) +
  geom_point(aes(x = as.integer(month), y = hue_norm), alpha = 0.1, size = 0.1) +
  scale_x_continuous(limits = c(temp$min_month[1], temp$max_month[1])) +
  facet_grid(method~class) +
  labs(x = "Month",
       y = "Normalized Hue",
       color = "Legend") +
  theme(legend.position = "bottom",
        legend.direction = "horizontal")

cluster_patterns

cluster_patterns %>%
  ggsave(filename = paste0("figs/", this_region, "_cluster_patterns.png"),
         width = 8,
         height = 8,
         dpi = 300)

## map

region_bbox = dat %>% 
  group_by(region) %>% 
  summarise(lat_min = min(clat),
            lat_max = max(clat),
            lon_min = min(clon),
            lon_max = max(clon)) %>% 
  ungroup()

require(ggmap)

this_region_bbox = region_bbox[region_bbox$region == this_region, ]
this_region = this_region_bbox$region

map = get_stamenmap(c(
  this_region_bbox$lon_min, 
  this_region_bbox$lat_min, 
  this_region_bbox$lon_max, 
  this_region_bbox$lat_max), maptype = "terrain", zoom = 9)

cluster_map = ggmap(map, darken = c(0.7, "black")) +
  geom_point(data = clustered %>% 
               inner_join(lake_info, by = "lake_id"), mapping = aes(x = clon, y = clat, color = class), alpha = 0.7) +
  scale_color_viridis_d(end = 0.8) +
  labs(title = paste("Lake color clusters: ", this_region),
     x = "Longitude",
     y = "Latitude",
     color = "Cluster") +
  facet_wrap(~method) +
  theme(title = element_text(size = 12))

cluster_map

cluster_map %>% 
  ggsave(filename = paste0("figs/", this_region, "_cluster_map.png"), 
         width = 8,
         height = 5,
         dpi = 300)

# merrged_map = cluster_map - doy_series_clustered +
#   plot_layout(ncol = 1) +
#   plot_annotation(tag_levels = "A")
# 
# merrged_map %>% 
#   ggsave(filename = paste0("figs/", this_region, "_merrged_cluster_map.png"),
#          width = 8,
#          height = 8)
```

## temporal changes

```{r}
doy_hue_index = doy_hue %>% 
  mutate(greenness = abs(mean_hue - 0.3),
         blueness = abs(mean_hue - 0.6),
         brownness = abs(mean_hue - 0.1))

## running window tibble
window_size = 8
increment = 5

start_dates = seq(1984, 2020, by = increment)
end_dates = start_dates + window_size

start_dates = as.Date(paste0(start_dates, "-01-01"))
end_dates = as.Date(paste0(end_dates, "-01-01"))

windowed = tibble(start_dates, end_dates) %>% 
  filter(end_dates <= as.Date("2020-01-01")) %>% 
  mutate(label = paste0(year(start_dates), "-", year(end_dates) - 1)) %>% 
  mutate(mean_year = floor((year(start_dates) + year(end_dates)) / 2)) %>% 
  group_by(label) %>% 
  do({
    dat = .
    doy_hue_index %>% 
      filter(date <= dat$end_dates[1], date >= dat$start_dates[1]) %>% 
      mutate(
        start_date = dat$start_dates[1],
        end_date = dat$end_dates[1], 
        mean_year = dat$mean_year[1])
  }) %>% 
  ungroup()


windowed %>% 
  ggplot() +
  geom_bar(aes(x = label, fill = region), position = "dodge") +
  theme(axis.text.x.bottom = element_text(angle = 45, hjust = 1))
# plot the data

greenness_mw = windowed %>% 
  filter(region == "Minnesota + Wisconsin") %>% 
  ggplot() +
  # geom_smooth(aes(x = doy, y = greenness, group = lake_id), lwd = 0.1, se = F, show.legend = F, color = "darkgreen") +
  # geom_point(aes(doy, y = greenness), size = 0.1, alpha = 0.1) + 
  geom_smooth(aes(x = doy, y = greenness, color = mean_year, group = mean_year)) +
  scale_y_reverse(minor_breaks = NULL, breaks = c(0.025, 0.275), labels = c("More green", "Less green"), lim = c(0.3, 0)) +
  labs(x = "Day of the year",
       y = "Greenness (hue ref: 0.3)",
       title = "Greenness for lakes from Minnesota + Wisconsin",
       color = "Centered year") +
  theme(axis.text.y.left = element_text(angle = 90, hjust = 0.5),
        axis.ticks.y = element_blank(),
        panel.grid.major.y = element_blank()) +
  scale_color_viridis_c()

greenness_mw

greenness_mw %>% ggsave(
  filename = "figures/mw_greenness_20200207_temporal.png",
  width = 8,
  height = 5,
  dpi = 300
)


brownness_mk = windowed %>% 
  filter(region == "Mackenzie Delta") %>% 
  ggplot() +
  # geom_smooth(aes(x = doy, y = greenness, group = lake_id), lwd = 0.1, se = F, show.legend = F, color = "darkgreen") +
  # geom_point(aes(doy, y = greenness), size = 0.1, alpha = 0.1) + 
  geom_smooth(aes(x = doy, y = brownness, color = mean_year, group = mean_year)) +
  scale_y_reverse(minor_breaks = NULL, breaks = c(0.025, 0.275), labels = c("More brown", "Less brown"), lim = c(0.3, 0)) +
  labs(x = "Day of the year",
       y = "Brownness (hue ref: 0.1)",
       title = "Brownness for lakes from Mackenzie Delta",
       color = "Centered year") +
  theme(axis.text.y.left = element_text(angle = 90, hjust = 0.5),
        axis.ticks.y = element_blank(),
        panel.grid.major.y = element_blank()) +
  scale_color_viridis_c()

brownness_mk

brownness_mk %>% ggsave(
  filename = "figures/mk_brownness_20200205_temporal.png",
  width = 8,
  height = 5,
  dpi = 300
)




lake_id_sample = windowed %>% 
  filter(region == "Minnesota + Wisconsin") %>% 
  select(lake_id) %>% 
  distinct() %>% 
  sample_n(10)

windowed %>% 
  filter(region == "Minnesota + Wisconsin") %>% 
  right_join(lake_id_sample, by = "lake_id") %>% 
  ggplot() +
  geom_smooth(aes(x = doy, y = greenness, color = mean_year, group = mean_year), lwd = 0.3, se = F) +
  # geom_point(aes(doy, y = greenness), size = 0.1, alpha = 0.1) + 
  # geom_smooth(aes(x = doy, y = greenness, color = mean_year, group = mean_year)) +
  scale_y_reverse(minor_breaks = NULL, breaks = c(0.025, 0.275), labels = c("More green", "Less green"), lim = c(0.3, 0)) +
  labs(x = "Day of the year",
       y = "Greenness (hue ref: 0.3)",
       title = "Greenness for lakes from Minnesota + Wisconsin",
       color = "Centered year") +
  theme(axis.text.y.left = element_text(angle = 90, hjust = 0.5),
        axis.ticks.y = element_blank(),
        panel.grid.major.y = element_blank()) +
  scale_color_viridis_c() +
  facet_wrap(~lake_id)
```



## time series spectral analysis

```{r}
require(spectral)

this_lake = dat %>% 
  filter(region == "Minnesota + Wisconsin",
         lake_id == 110) %>% 
  mutate(t = as.integer(date - as.Date("1983-01-01")) / 365.25)

ymean = mean(this_lake$hue)

this_lake = this_lake %>% 
  mutate(y = hue - ymean)

this_lake %>% ggplot() + geom_point(aes(yday(date), hue))
this_lake %>% ggplot() + geom_line(aes(t, hue), color = "grey") + geom_point(aes(t, hue))

periodogram = spec.lomb(x = this_lake$t, y = this_lake$y, ofac = 20, mode = "generalized")

plot(periodogram)

# select a frequency range
m = c(0.02, 4)
# select and reconstruct the most significant component
l2 = filter.lomb(periodogram, newx = seq(0, 35.5, length = 1000), filt = m, threshold = 6)

plot(this_lake$t, this_lake$y, type = "p")
lines(this_lake$t, this_lake$y)
lines(l2$x, l2$y, col = "red")
```


<!-- ## hydrolakes -->

<!-- ```{r} -->
<!-- dat = read_csv(file = "data/lake_color_f247c809ee74fd2458b96420f42f876d.csv") %>%  -->
<!--   select(-`.geo`) %>%  -->
<!--   rename(img_id = `system:index`) -->

<!-- dat = dat %>%  -->
<!--   mutate(date = as.Date(substr(img_id, start = 15, stop = 22), format = "%Y%m%d")) %>%  -->
<!--   filter(cloudAndShadow == 0, -->
<!--          snowAndIce == 0) %>%  -->
<!--   select( -->
<!--     clon, -->
<!--     clat, -->
<!--     img_id, -->
<!--     Hylak_id, -->
<!--     date, -->
<!--     hue, -->
<!--     saturation, -->
<!--     value -->
<!--   ) -->

<!-- dat %>%  -->
<!--   ggplot() + -->
<!--   geom_density(aes(hue, color = Hylak_id)) -->

<!-- calc_hue_density = function(hue) { -->

<!--   d = density(hue, n = 512) -->

<!--   hue_density = tibble(hue = d$x, density = d$y) %>%  -->
<!--     filter(hue >= 0, hue <= 1) %>%  -->
<!--     mutate(rgb_color = hsv(h = hue, s = 1, v = 1)) -->

<!--   return(hue_density) -->
<!-- } -->
<!-- calc_hue_color_bar = function(n = 100) { -->
<!--   return(tibble(hue = seq(0, 1, length = n)) %>% mutate(rgb_color = hsv(h = hue, s = 1, v = 1))) -->
<!-- } -->

<!-- hue_density = calc_hue_density(dat$hue) -->


<!-- MN_lake_color = hue_density %>%  -->
<!--   ggplot(aes(hue, density)) +  -->
<!--   geom_segment(aes(xend = hue, yend = 0, color = rgb_color), alpha = 0.7) +  -->
<!--   geom_line(lwd = 1) +  -->
<!--   scale_color_identity() + -->
<!--   scale_x_continuous(limits = c(0, 1), expand = c(0, 0)) + -->
<!--   labs( -->
<!--     y = "Density" -->
<!--   ) + -->
<!--   theme( -->
<!--     panel.background = element_blank(), -->
<!--     axis.title = element_blank(), -->
<!--     axis.text = element_blank(), -->
<!--     axis.ticks = element_blank() -->
<!--   ) -->

<!-- MN_lake_color -->


<!-- ## per lake density plot -->

<!-- hue_density_lake = dat %>%  -->
<!--   group_by(Hylak_id) %>%  -->
<!--   do({ -->
<!--     calc_hue_density(.$hue) %>%  -->
<!--       mutate(n = nrow(.)) -->
<!--   }) %>%  -->
<!--   ungroup() -->

<!-- yshift = hue_density_lake %>%  -->
<!--   group_by(Hylak_id) %>%  -->
<!--   summarize(ymax = max(density)) %>%  -->
<!--   ungroup() %>%  -->
<!--   arrange(ymax) %>%  -->
<!--   select(Hylak_id) %>% -->
<!--   mutate(yshift = 1:nrow(.)) -->

<!-- hue_density_lake = hue_density_lake %>%  -->
<!--   left_join(yshift, by = "Hylak_id") -->

<!-- yscale = hue_density_lake %>% group_by(Hylak_id) %>% summarize(stats = median(density)) %>% ungroup() %>% pull(stats) %>% quantile(probs = 0.1) -->

<!-- MN_lake_color_per_lake = hue_density_lake %>%  -->
<!--   ggplot(aes(hue, density + yshift * yscale)) +  -->
<!--   # geom_segment(data = calc_hue_color_bar(n = 512), aes(x = hue, y = 0, xend = hue, yend = hue_density_lake$density %>% max * 0.02, color = rgb_color), alpha = 1) + -->
<!--   # geom_line(aes(group = Hylak_id), alpha = 0.1) + -->
<!--   geom_segment(aes(xend = hue, yend = yshift * yscale, color = rgb_color, group = Hylak_id), alpha = 0.1) +  -->
<!--   scale_color_identity() + -->
<!--   scale_x_continuous(limits = c(0, 1), expand = c(0, 0)) + -->
<!--   labs( -->
<!--     y = "Density" -->
<!--   ) + -->
<!--   theme( -->
<!--     panel.background = element_rect(color = "black", fill = "black"), -->
<!--     panel.grid = element_blank(), -->
<!--     axis.title = element_blank(), -->
<!--     axis.text = element_blank(), -->
<!--     axis.ticks = element_blank() -->
<!--   ) -->

<!-- MN_lake_color_per_lake -->

<!-- MN_lake_color_per_lake %>%  -->
<!--   ggsave(filename = "figures/MN_lake_color_per_lake.png", -->
<!--          width = 8, -->
<!--          height = 6, -->
<!--          dpi = 100) -->
<!-- ``` -->