---
title: "Lake variables"
author: "Xiao Yang"
date: "2/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(sf)
require(tidyverse)
```

## Merge attributes, excluding landcover and hydrolake attributes

### lake center

```{r}
lake_coords = st_read("outputs/lakeSample_Dp.geojson") %>% 
  distinct(.keep_all = T) %>% 
  select(id)

lake_latlon = lake_coords %>% select(id) %>% mutate(
  lon = st_coordinates(geometry)[, 1],
  lat = st_coordinates(geometry)[, 2]
) %>% st_drop_geometry() %>% 
  as_tibble()

lake_latlon = lake_latlon %>% mutate(
  hemisphere = cut(lat, breaks = c(min(lat), 0, max(lat)), labels = c("S", "N"), include.lowest = T)
)
```

### mean lake water occ

```{r}
## add lake mean water occ
meanLakeOcc = dir(path = "data/meanLakeOcc/", pattern = ".csv", include.dirs = T, full.names = T) %>% 
  map(read_csv, col_types = "cn") %>% 
  reduce(bind_rows)

summary(meanLakeOcc)

meanLakeOcc %>% dplyr::select(id) %>% distinct %>% nrow() ## 150,559 lakes - 368 lakes
```

### overall climate variables

```{r}
k2c = 273.15

era5lake = dir("data/lakeTempPrecip", full.names = T) %>% 
  map(read_csv, col_types = "cnnnn") %>% 
  reduce(bind_rows) %>% 
  mutate(mean_2m_air_temperature_mean = mean_2m_air_temperature_mean - k2c)
```

### seasonal climate variables

```{r}
seasonal_climate = dir(path = "data/LakeTempPrecip_min_d6fed587b373455c77b5f31a9e16c346", pattern = ".csv", full.names = T, include.dirs = T) %>% 
  map(read_csv, col_type = paste0("c", paste(rep("n", 20), collapse = ""))) %>% 
  reduce(bind_rows)

seasonal_climate = seasonal_climate %>% 
  select(
    -mean_2m_air_temperature_mean, 
    -mean_2m_air_temperature_stdDev, 
    -total_precipitation_mean, 
    -total_precipitation_stdDev) %>% 
  select(ends_with("mean"), id)

k2c = 273.15

seasonal_climate = seasonal_climate %>% 
  mutate(
    spring_temperature_mean = spring_temperature_mean - k2c,
    summer_temperature_mean = summer_temperature_mean - k2c,
    fall_temperature_mean = fall_temperature_mean - k2c,
    winter_temperature_mean = winter_temperature_mean - k2c)

lake_latlon

nhLakes = seasonal_climate %>% 
  inner_join(lake_latlon %>% filter(hemisphere == "N"), by = "id")

shLakes = seasonal_climate %>% 
  inner_join(lake_latlon %>% filter(hemisphere == "S"), by = "id")

shLakes1 = shLakes %>% 
  mutate(
    spring_temperature_mean = fall_temperature_mean,
    summer_temperature_mean = winter_temperature_mean,
    spring_total_precipitation_mean = fall_total_precipitation_mean,
    summer_total_precipitation_mean = winter_total_precipitation_mean
    )

shLakes2 = shLakes %>% 
  mutate(
    fall_temperature_mean = spring_temperature_mean,
    winter_temperature_mean = summer_temperature_mean,
    fall_total_precipitation_mean = spring_total_precipitation_mean,
    winter_total_precipitation_mean = summer_total_precipitation_mean
    )

shLakes = shLakes1 %>% 
  select(id, 
         spring_temperature_mean, 
         summer_temperature_mean, 
         spring_total_precipitation_mean,
         summer_total_precipitation_mean) %>% 
  bind_cols(shLakes2 %>% 
              select(fall_temperature_mean,
                     winter_temperature_mean,
                     fall_total_precipitation_mean,
                     winter_total_precipitation_mean))

seasonalLakes = nhLakes %>% select(
  id, 
  spring_temperature_mean, 
  summer_temperature_mean, 
  fall_temperature_mean,
  winter_temperature_mean,
  spring_total_precipitation_mean,
  summer_total_precipitation_mean,
  fall_total_precipitation_mean,
  winter_total_precipitation_mean
) %>% bind_rows(shLakes)
```

### lake physical parameters

```{r}
lakeMeta = read_csv("outputs/lake_meta_v2.csv", col_types = "iccnnc")
lakeElev = read_csv("data/lake_center_elevation_038ec249d09358b3715e0f02c89e6d98.csv", col_types = "cnn")
lakeMetric = read_csv("data/lakeMetrics_022b85da71a43d98e7c2cea22c6c0c66.csv")

lakeElev = lakeElev %>% 
  group_by(id) %>% 
  summarise(elevation = median(dem, na.rm = T),
            dist_to_shore = min(distance, na.rm = T))

load("outputs/dat_just_modal_color_2022.RData", verbose = T)

model_input = datMode %>% 
  left_join(meanLakeOcc %>% rename(occ_mean = lakeMeanOcc), by = "id") %>% 
  left_join(era5lake, by = "id") %>% 
  left_join(seasonalLakes, by = "id") %>% 
  left_join(lakeMeta %>% select(-lakeName, -source) %>% rename(depth_mean = depthMean), by = "id") %>% 
  left_join(lakeElev %>% distinct(), by = "id") %>% 
  left_join(lakeMetric %>% rename(lake_area = polygonArea), by = "id") %>% 
  mutate(
    lake_area = lake_area / 1000000,
    volumn = lake_area * depth_mean / 1000) %>% 
  filter(!is.na(elevation), !is.na(dist_to_shore), !is.na(occ_mean), !is.na(class))

model_input %>% summary()

save(model_input, file = "outputs/20220211_model_input.RData")
```

